language: node_js
node_js:
- '5'
before_install:
- npm install istanbul mocha -g
install:
- npm install
before_script:
- npm link .
script:
- ./ci/build.js
- ./ci/test.js
- ./ci/cover.js
- ./ci/report.js
